"""adds boat_profiles and boat_specifications table

Revision ID: 6dbf5700fc2b
Revises:
Create Date: 2026-06-28 10:24:39.052744

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dbf5700fc2b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boat_specifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("builder", sa.String(), nullable=True),
        sa.Column("construction", sa.String(), nullable=True),
        sa.Column("designer", sa.String(), nullable=True),
        sa.Column("first_built", sa.Integer(), nullable=True),
        sa.Column("hull_type", sa.String(), nullable=True),
        sa.Column("last_built", sa.Integer(), nullable=True),
        sa.Column("make", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("dimensions_ballast_kg", sa.Integer(), nullable=True),
        sa.Column("dimensions_beam_mm", sa.Integer(), nullable=False),
        sa.Column("dimensions_displacement_kg", sa.Integer(), nullable=True),
        sa.Column("dimensions_draft_mm", sa.Integer(), nullable=False),
        sa.Column("dimensions_loa_mm", sa.Integer(), nullable=False),
        sa.Column("dimensions_lwl_mm", sa.Integer(), nullable=False),
        sa.Column("engine_cooling", sa.String(), nullable=True),
        sa.Column("engine_drive", sa.String(), nullable=True),
        sa.Column("engine_fuel_type", sa.String(), nullable=True),
        sa.Column("engine_gearbox", sa.String(), nullable=True),
        sa.Column("engine_horsepower_hp", sa.Integer(), nullable=True),
        sa.Column("engine_make", sa.String(), nullable=True),
        sa.Column("engine_model", sa.String(), nullable=True),
        sa.Column("engine_propeller", sa.String(), nullable=True),
        sa.Column("rigging_e_mm", sa.Integer(), nullable=True),
        sa.Column("rigging_forestay_length_mm", sa.Integer(), nullable=True),
        sa.Column("rigging_i_mm", sa.Integer(), nullable=True),
        sa.Column("rigging_j_mm", sa.Integer(), nullable=True),
        sa.Column("rigging_p_mm", sa.Integer(), nullable=True),
        sa.Column("rigging_type", sa.String(), nullable=True),
        sa.Column("sail_area_fore_cm2", sa.Integer(), nullable=True),
        sa.Column("sail_area_main_cm2", sa.Integer(), nullable=True),
        sa.Column("sail_area_reported_cm2", sa.Integer(), nullable=True),
        sa.Column("tanks_fuel_capacity_l", sa.Integer(), nullable=True),
        sa.Column("tanks_water_capacity_l", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "boat_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("specification_id", sa.UUID(), nullable=False),
        sa.Column("call_sign", sa.String(), nullable=True),
        sa.Column("home_port", sa.String(), nullable=True),
        sa.Column("hin", sa.String(), nullable=False),
        sa.Column("image_uri", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["specification_id"], ["boat_specifications.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("boat_profiles")
    op.drop_table("boat_specifications")
    # ### end Alembic commands ###
