"""adds boats_profiles table

Revision ID: fcdaaa3aa3c1
Revises:
Create Date: 2026-06-28 09:23:57.997384

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fcdaaa3aa3c1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boat_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("call_sign", sa.String(), nullable=True),
        sa.Column("home_port", sa.String(), nullable=True),
        sa.Column("hin", sa.String(), nullable=False),
        sa.Column("image_uri", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("boat_profiles")
    # ### end Alembic commands ###
